### ISSUE TITLE
400 (Bad Request) on own server

### ISSUE THREAD

**Issue by dottodot** [betamax/getImageData#12]
I'm trying to get this working on my own server but I always get a 400(Bad Request)

Here's my code

```
            $.getImageData({
                url: soundcloud.artwork_url,
                server: "http://127.0.0.1:3000/",
                success: function(image) {
                    console.log(image);
                },
                error: function(xhr, text_status) {
                    console.log(xhr, text_status);
                }
            });
```

Any idea as to what could be causing this?

**Comment by betamax** [comment]
Hmm. What does `soundcloud.artwork_url` look like? I haven't looked at the node code for a long time, maybe some packages have stopped the code working.. 

I'm guessing you've read all the information here: https://github.com/betamax/getImageData/tree/master/server-examples/node

**Comment by dottodot** [comment]
The soundcloud.waveform_url (sorry was wrong in my first post) has a value of http://w1.sndcdn.com/jsFp5H3DhnLC_m.png

This is the error I'm seeing.
GET http://127.0.0.1:3000/?callback=_jqjsp&url=http%253A%2F%2Fw1.sndcdn.com%2FjsFp5H3DhnLC_m.png&_1394120590380= 400 (Bad Request)

Been through the info and not missed anything

**Comment by betamax** [comment]
I think aab23bc18fe43aa432cca63162952749627eb161 should fix this issue. You'll need to pull the changes and run `npm install` inside the `server-examples/node` folder to install dependencies. Please report back if it works or not for you!

**Comment by betamax** [comment]
@dottodot Could you confirm this was fixed? I'd like to close the issue if so.

**Comment by deweydb** [comment]
I am also having this problem, with the following soundcloud image: https://w1.sndcdn.com/5NhYvVQ5kZjk_m.png

**Comment by deweydb** [comment]
Oh, i see:
Over Quota
This application is temporarily over its serving quota. Please try again later.

Could your provide the server side implementation so we could run this on our own server?

**Comment by deweydb** [comment]
Jesus, i'm an idiot, i didn't even see your server examples. nevermind.

**Comment by betamax** [comment]
I think the server examples are quite important, maybe I should make them a bit more obvious. I hope you got it working!
