### ISSUE TITLE
getting getImageData.py running on GAE

### ISSUE THREAD

**Issue by forresto** [betamax/getImageData#3]
Are there any directions for getting getImageData.py running on GAE?

**Comment by betamax** [comment]
[Here is a link to the google app engine project](https://www.dropbox.com/s/cn35nv2mo42rw86/getimagedata_gae.zip). I'm afraid I can't remember what exactly I did to get it up and running; those files are the ones that are currently on the server so I think it's just a matter of deploying them to your GAE account/project. Some references to help you along are below and feel free to ask me about any further questions you have:
- [Django on Google App Engine in 13 easy steps](http://thomas.broxrost.com/2008/04/08/django-on-google-app-engine/)
- [Uploading your application](http://code.google.com/appengine/docs/python/gettingstarted/uploading.html)

Also, I know that Google have just changed their pricing rules for GAE but I haven't really noticed any differences, so hopefully you should be fine with that.

Hope that helps! I add this code and instructions to the repo as soon as I can.

**Comment by forresto** [comment]
Thanks! 

I actually ended up going with [PHP Fog](https://phpfog.com/). They don't allow `file_get_contents` on non-local files, so I used curl, replacing [line 33](https://github.com/betamax/getImageData/blob/master/server-examples/getImageData.php#L33):

```
$file = file_get_contents($url);
```

with:

```
$ch = curl_init();
// set URL and other appropriate options
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, 0);
$file = curl_exec($ch);
curl_close($ch);
```
