### ISSUE TITLE
A question about jsonp

### ISSUE THREAD

**Issue by woto** [betamax/getImageData#7]
Hi, sorry for bad English. I think i'ts bad to store this library in yours.

ps. Just made you library to work with jquery-file-upload. Cool! Thanks for good work.

**Comment by betamax** [comment]
Hey @woto,

Thanks for your comment. I guess I could look at doing something like including [jquery-jsonp](https://github.com/jaubourg/jquery-jsonp) as a [submodule](http://stackoverflow.com/questions/2140985/setup-a-git-external-for-remote-repo) and then when compiling the minified script, concatenate them together? I included it to keep things simpler for people so they don't have to manage too many dependencies.

Glad you got the library working with jquery-file-upload sounds cool!

Max

**Comment by woto** [comment]
Yes it's good idea. Much better if there is a demo with prerequisite described in it. For example for now i use you library in Ruby on Rails application, which used technics called as Assets Pipeline which concatenates and compress libriaries togeter http://guides.rubyonrails.org/asset_pipeline.html
