### ISSUE TITLE
In iOS, tap on a hyperlink and canvases of other hyperlinks disappear, too.

### ISSUE THREAD

**Issue by ianthedev** [betamax/getImageData#9]
In iOS, after tapping on a hyperlink, its grayscale image (canvas) disappears, and that's the correct behavior. However, canvases of other hyperlinks incorrectly disappear, too.

Please try it using the [live example](http://www.pryde-design.co.uk/projects/jQGreyScale/example.html) page. It may be unnoticeable when there is only one such hyperlink, but it becomes noticeable when there are ten or more.

And tapping on other regular hyperlinks (which don't implement this grayscale effect) causes the same issue.

**Comment by betamax** [comment]
I'm not sure this is anything to do with the getImageData plugin itself. It seems as though this is to do with the implementation of the hovers. You might want to ask about this on the $.GreyScale repository: https://github.com/Prydie/jQuery-GreyScale-Plugin repository.
